---

- hosts: 127.0.0.1
  connection: local
  become: true
  tasks:

    - name: Copy Kubernetes Manifests from GitHub
      copy:
        src: ../kubernetes/
        dest: /home/ubuntu/kubernetes/
        mode: "777"

    - name: Copy sutupDocker.sh from GitHub
      copy:
        src: ../sutupDocker.sh
        dest: /home/ubuntu/
        mode: "777"

    - name: Run sutupDocker.sh
      become: true
      shell: "sudo ./sutupDocker.sh -y"

    - name: Run sudo usermod -aG docker $USER 
      become: true
      shell: "sudo chmod 666 /var/run/docker.sock"
    




    

    

