---

- hosts: EC2_server
  become: true
  tasks:

    - name: Copy Kubernetes Manifests from GitHub
      copy:
        src: ../kubernetes/
        dest: /home/ubuntu/kubernetes/
        mode: "777"

    - name: Copy sutupDocker.sh from GitHub
      copy:
        src: ../sutupDocker.sh
        dest: /home/ubuntu/
        mode: "777"

    - name: Run sutupDocker.sh
      become: true
      shell: "sudo ./sutupDocker.sh -y"

    - name: Run sudo systemctl enable docker
      become: true
      shell: "sudo systemctl enable docker"

    - name: Run sudo systemctl start docker
      become: true
      shell: "sudo systemctl start docker"

    - name: Run sudo usermod -aG docker $USER 
      become: true
      shell: "sudo usermod -aG docker $USER"
    
    - name: Run newgrp docker
      become: true
      shell: "sudo newgrp docker"

    



    

    

