---

- hosts: EC2_server
  become: true
  tasks:

    - name: Delete Minikube
      become: false
      shell: "minikube delete --all"

    - name: Start Minikube
      become: false
      shell: "sudo minikube start --force --driver=docker"
 
    - name: Apply Kubernetes Manifests for mongo
      become: false
      shell: "kubectl apply -f /home/ubuntu/kubernetes/mongo.yml"

    - name: Wait for mongo pod to be running
      become: false
      shell: |
        until kubectl get pods -l app=mongo | grep -m 1 '1/1'; do
          sleep 1
        done

    - name: Apply Kubernetes Manifests
      become: false
      shell: "kubectl apply -f /home/ubuntu/kubernetes/"


    


