name: etherpad-build
run-name: Docker Image etherpad Push

on:
  push:
    branches:
      - main
    paths:
      - 'etherpad-lite/**'

jobs:
  etherpad-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into Docker Hub registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Etherpad Docker image
      working-directory: ./etherpad-lite
      run: |
        docker build -t ciccio2305/justsmartetherpad:latest .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ciccio2305/justsmartetherpad:latest