name: deploy
run-name: App Deploy

on:
  workflow_run:
    workflows: ["dockerimage"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    #----------------------------------------#
    #   Deploy on AWS EC2 by using Ansible   #
    #----------------------------------------#

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy by using Ansible Playbook Part 1
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ./ansible/playbook.yml
          key: ${{ secrets.AWS_SSH_KEY }}
          inventory: |
            [EC2_server]
            ${{ secrets.EC2_DOMAIN }} ansible_user=${{ secrets.EC2_USER }}

      - name: Deploy by using Ansible Playbook Part 2
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ./ansible/playbook2.yml
          key: ${{ secrets.AWS_SSH_KEY }}
          inventory: |
            [EC2_server]
            ${{ secrets.EC2_DOMAIN }} ansible_user=${{ secrets.EC2_USER }}